#!/bin/sh

# NOTES
# addq (add quote): add the input to the quote file.  Accepts one argument (the
# body of the quote in sanitized form), but you really should be using this with
# pipes so you don't have to sanitize it yourself (see USAGE->Example(s)).
#
# USAGE
# echo '[sanitized form of quote]' | addq
# cat [file containing sanitized form of quote] | addq

. ./config
. ./lockq

# Determine id of the last quote, and add one to it for the quote to be added
ID=`tail -1 quotes | cut -d : -f 1`
ID=`expr $ID + 1`

# Replace the input quote with something of the form "$ID:0:u:input", where
# "$ID" is the id of the new quote and "input" is the input of the scrupt.  Then
# write the result to the quotes file.
sed -r 's/(.*)/'$ID':0:u:\1/' >>$qfile

. ./ulockq
