#!/bin/bash

# NOTES
# config (configuration variables): This is not a shell script.  This defines
# some variables and paths and names (in case you want to change them).

# qfile is the path to the file that stores all the quotes.
# Default: ./quotes
qfile=./quotes

# qlockfile is the path to the file that is used by lockq and ulockq for
# queueing operations that modify the quotes file.
# Default: ./quotes.lock
qlockfile=./quotes.lock
