#!/bin/sh
awk -F:: '
$3=="t"{
print "<div class=\"quote\">"
print "<span class=\"qid\">"$1"</span>"
print "<span class=\"qscore\">"$2"</span>"
print "<div class=\"qcontent\">"
system ("echo '\''"$NF"'\'' | ./unescq  | outq/html")
print "</div>"
print "</div>"
}
' | ./unescq
