#!/bin/sh

# NOTES
# getq (get quote): return a specified range of quotes, with metadata.
#
# USAGE
# getq [min quote id] [max quote id]
# getq [quote id]
# Example(s):
# getq 2 5
#  Comment: this retrieves quotes 2, 3, 4, and 5
# getq 5 2
#  Comment: the order of min/max does not matter
# getq 4
#  Comment: this retrieves quote 4
# getq 4 4
#  Comment: this retrieves quote 4
# getq
#  Comment: this retrieves all quotes

. ./config

# Check how many command-line arguments are given
case $# in
	0)
		# Return all contents of the quotes file
		sed -n /^::/p <$qfile;
		;;
	1)
		# Return the quote specified by the argument
		sed -n /^$1::/p <$qfile;
		;;
	2)
		# Return the range of quotes specified by the min and max, inclusive
		if [ $1 -eq $2 ]; then
			# Return the quote specified by the two arguments (which are equal)
			sed -n /^$1::/p <$qfile;
		elif [ $1 -gt $2 ]; then
			# If the first argument is the larger of the two arguments, use it as a max
			sed -n /^$2::/,/^$1::/p <$qfile;
		else
			# If the second argument is the larger of the two arguments, use it as a max
			sed -n /^$1::/,/^$2::/p <$qfile;
		fi
		;;
	*)
		echo "Error: Invalid quote range specification.";
		;;
esac
