#!/bin/sh

# NOTES
# lockq (lock quote): lockq puts files that modify the quote db into a queue to
# avoid collisions/overwriting. It's meant to be used along with ulockq.

while [ -e $qlockfile ]
do /bin/true
done
touch $qlockfile
