#!/bin/sh

# This waits until the lock file is gone, and then creates its own.
# Basically, including this puts a lock on the file, ensuring sequential
# access. 
# 
# Usage
# . lockq
# do shit here to quotes
# . ulockq # removes the lock
#
# see setqf for an example.

. config

while [ -e $qlockfile ]
do env sleep .05s
done
touch $qlockfile
