#!/bin/sh

# NOTES
# setqf (set quote flag): set the third flag in the quote file.  This flag can
# have any value, but it is meant for 3 possible values: u, a, and h
#
# USAGE
# setqf [quote id] [flag]

. ./config
. ./lockq

# First find the line with the correct id; replace [id]::[score]::[oldflag]::[quote] with [id]::[score]::[newflag]::[quote]
sed -r -i '/^'$1'::/ s/([0-9]+::)([0-9]+::)(.)(::.)/\1\2'$2'\4/' $qfile

. ./ulockq

