#!/bin/sh

# NOTES
# setqscore (set quote score): modify a quote's score/rating/quality/etc.
# Accepts 3 arguments:
#  up: increment the score by one.
#  down: decrement the score by one.
#  (any numerical argument): set the score to the value provided.
#
# USAGE
# setqscore [quote id] [option]

. ./config
. ./lockq

CURRENTSCORE=`awk 'BEGIN{FS="::"}{if($1=='$1')print $2;}' <$qfile`

if [ "$2" = "up" ]; then
	NEWSCORE=`expr $CURRENTSCORE + 1`
elif [ "$2" = "down" ]; then
	NEWSCORE=`expr $CURRENTSCORE - 1`
else
	NEWSCORE="$2"
fi

# First find the line with the correct id; replace [id]::[oldscore]::[flag]::[quote] with [id]::[newscore]::[flag]::[quote]
sed -r -i '/^'$1'::/ s/([0-9]+::)([0-9]*)(::.*)(::.*)/\1'$NEWSCORE'\3\4/' $qfile

. ./ulockq

