#!/bin/sh

# NOTES
# setqscore (set quote score): modify a quote's score/rating/quality/etc.
# Accepts 3 arguments:
#  up: increment the score by one.
#  down: decrement the score by one.
#  (any numerical argument): set the score to the value provided.
#
# USAGE
# setqscore [quote id] [option]

. ./config
. ./lockq

if [ $2 = up ]; then
	awk 'BEGIN{FS="::"; OFS="::";}{if($1=='$1')$2++;print;}' <$qfile >$qtempfile
elif [ $2 = down ]; then
	awk 'BEGIN{FS="::"; OFS="::";}{if($1=='$1')$2--;print;}' <$qfile >$qtempfile
else
	awk 'BEGIN{FS="::"; OFS="::";}{if($1=='$1')$2='$2';print;}' <$qfile >$qtempfile
fi
mv $qtempfile $qfile

. ./ulockq

