#!/bin/sh

# NOTES
# setqscore (set quote score): modify a quote's score/rating/quality/etc.
# Accepts 3 arguments:
#  up: increment the score by one.
#  down: decrement the score by one.
#  (any numerical argument): set the score to the value provided.
#
# USAGE
# setqscore [quote id] [option]
# Example(s):
# setqscore 1 up
# setqscore 2 down
# setqscore 4 9001

. config
. lockq

if [ $2 = up ]; then
	awk -F:: 'BEGIN{OFS="::";}{if($1=='$1')$2++;print;}' <$qfile >$qtempfile
elif [ $2 = down ]; then
	awk -F:: 'BEGIN{OFS="::";}{if($1=='$1')$2--;print;}' <$qfile >$qtempfile
else
	awk -F:: 'BEGIN{OFS="::";}{if($1=='$1')$2='$2';print;}' <$qfile >$qtempfile
fi
mv $qtempfile $qfile

. ulockq

