#!/bin/sh

# NOTES
# setqq (set quote quote): set the quote in the quote file to a new one.  It
# reads the new quote from stdin.

#
# USAGE
# echo [new quote] | setqq [quote id]

. ./config
. ./lockq

# Because sanitized quotes are one-liners, we will only accept one line
read INPUT

# First find the line with the correct id; replace [id]::[score]::[flag]::[oldquote] with [id]::[score]::[flag]::[newquote]
sed -r -i '/^'$1'::/ s/([0-9]+::)([0-9]+::)(.*::)(.*)/\1\2\3'"$INPUT"'/' $qfile

. ./ulockq

