#!/bin/sh

case $1 in
	f)
		if [ "$2" != "" ]; then
			awk -F:: '$3 == "'$2'" {print;}'
		else
			cat
		fi
		;;
	s)
		case $2 in
			gt)
				COMPARISON='>'
				;;
			lt)
				COMPARISON='<'
				;;
			ge)
				COMPARISON='>='
				;;
			le)
				COMPARISON='<='
				;;
			eq)
				COMPARISON='=='
				;;
			ne)
				COMPARISON='!='
				;;
			*)
				;;
		esac

		if [ "$3" != "" ]; then
			awk -F:: '$2 '"$COMPARISON"' '"$3"' {print;}'
		else
			cat
		fi
		;;
	*)
		echo "Error: Invalid function specification."
		;;
esac
