#!/bin/sh

# NOTES
# ulockq (unlock quote): This removes the lock file (unlocks the quotes file).
# See lockq for documentation, usage, details, and mechanism.
#
# USAGE
# . ./lockq
# modify quotes or call on a script or do something else
# . ./ulockq
# Example(s):
# Comment: The source of setqf is an example of how ulockq is used in a script.

rm $qlockfile
