#!/bin/sh

# NOTES
# stripcrlf (strip cr lf): convert dos-type newlines to unix-type newlines.
# Use it in a pipeline, or something.
#
# USAGE
# echo '[literal form of quote(s)]' | stripcrlf
# cat [file with quote(s)] | stripcrlf

tr -d '\r'
