#!/usr/bin/awk -f

# NOTES
# fortune: convert all quotes from input to fortune format.  Meant to be used
# with pipes.
# 
# Accepts one argument: the input to be converted
#
# USAGE
# fortune [quotes to be converted]
# Example(s):
# fortune '10::0::u::<Colin> Foobar'
#  Comment: This will return:
#   <Colin> Foobar
#   %
#

BEGIN{FS="::";}
{print $4"\n%";}
