#!/usr/bin/awk -f
 
# NOTES
# fortune: convert all quotes from input to fortune format.  Meant to be used
# with pipes.
# 
# Accepts no arguments.
#
# USAGE
# echo 'quotes to be converted' | outq/fortune/fortune
# Example(s):
# echo '10::0::u::<Colin> Foobar' | fortune 
#  Comment: This will return:
#   <Colin> Foobar
#   %
#
BEGIN{FS="::";}
{print $4"\n%";}
