#!/bin/bash

TEXT=`cat`

until [ -z "$1" ]; do
	case $1 in
	-f)
		TEXT=`printf "%s" "$TEXT" | awk -F: '$3 == "'$2'" {print;}'`
		shift 2
		;;
	-s)
		case $2 in
			gt)
				COMPARISON='>'
				;;
			lt)
				COMPARISON='<'
				;;
			ge)
				COMPARISON='>='
				;;
			le)
				COMPARISON='<='
				;;
			eq)
				COMPARISON='=='
				;;
			ne)
				COMPARISON='!='
				;;
			*)
				;;
		esac

		TEXT=`printf "%s" "$TEXT" | awk -F: '$2 '"$COMPARISON"' '"$3"' {print;}'`
		shift 3
		;;
	*)
		echo "Error: Invalid function specification."
		break
		;;
	esac
done

printf "%s\n" "$TEXT"
