#!/bin/bash

# Get standard input and store it as a variable
INPUT=`cat`

# Count how many lines are in stdin
LINECOUNT=`echo "$INPUT" | wc -l`
# Determine how many quotes to randomly select
MAXCOUNT=$1

for i in `seq $MAXCOUNT`
do
	LINENUMBER=`expr $RANDOM % $LINECOUNT`
	echo "$INPUT" | sed $LINENUMBER'q;d' # using 'q;d' is equivalent to using 'p', but faster
done
