#!/bin/sh

# NOTES
# shows (show based on score): shows all quotes in stdin which match a bash
# comparison condition

case $1 in
	gt)
		COMPARISON='>'
		;;
	lt)
		COMPARISON='<'
		;;
	ge)
		COMPARISON='>='
		;;
	le)
		COMPARISON='<='
		;;
	eq)
		COMPARISON='=='
		;;
	ne)
		COMPARISON='!='
		;;
esac

awk -F:: '$2 '"$COMPARISON"' '"$2"' {print;}'
