#!/bin/sh

# NOTES
# fortune: This grab everything on stdin, and for all lines between each '%',
# add the lines to the quotesfile.
#
# USAGE
# cat [fortune file] | inq/fortunes

while read LINE; do
	if [ "$LINE" = '%' ]; then
		printf "%s\n" "$QUOTE" | escq | addq
		QUOTE=""
	else
		if [ "$QUOTE" = "" ]; then
			QUOTE="$LINE"
		else
			QUOTE="${QUOTE}\n${LINE}"
		fi
	fi
done
